version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my-mssql-server
    ports:
      - "1431:1433"  
    environment:
      - ACCEPT_EULA=Y  
      - SA_PASSWORD=pass@123
    volumes:
      - type: 'bind'
        target: '/var/opt/mssql/data'
        source: './docker/sqldata/data'
  
  wolfden: 
    image: wolfii:latest
    